export const REGISTER = "REGISTER";

export const LOGIN = "LOGIN";

export const DANG_NHAP_THANH_CONG = "DANG_NHAP_THANH_CONG";
export const DANG_NHAP_THAT_BAI = "DANG_NHAP_THAT_BAI";

export const DANG_XUAT = "DANG_XUAT";

export const LAY_DANH_SACH_USER = "LAY_DANH_SACH_USER";
export const USER_CURRENT = "USER_CURRENT";
export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";

export const UP_COMMENT = "UP_COMMENT";

export const LAY_THONG_TIN_TAI_KHOAN = "LAY_THONG_TIN_TAI_KHOAN";

export const CAP_NHAT_THANH_CONG = "CAP_NHAT_THANH_CONG";
